### ISSUE TITLE
Margin protocol RPC

### ISSUE THREAD

**Issue by xlc** [laminar-protocol/laminar-chain#173]
- margin_traderInfo(AccountId)
  - Response:
    - margin held
    - free margin
    - unrelaized pl
    - equity
    - margin level

- margin_poolInfo(PoolId)
  - Response
    - enp
    - ell

**Comment by ermalkaleci** [comment]
@xlc what is `margin balances`?

**Comment by xlc** [comment]
It suppose to be https://github.com/laminar-protocol/laminar-chain/blob/4cff2cace5e326d39ef5a14aba5e0febdb0e0cd9/modules/margin-protocol/src/lib.rs#L82

But frontend can just read it from storage so no need to get from RPC
