### ISSUE TITLE
Margin protocol next version

### ISSUE THREAD

**Issue by xlc** [laminar-protocol/laminar-chain#196]
- Split margin balances
  - Instead of trader have one margin balances, make it per pool
- Liquidity Pool Threshold (ENP & ELL)
  - The thresholds are configured per trading pair
  - The threshold value used for liquidity pool is the max of all its supported pairs & opened pairs
    - Liquidity pool may choose to disable a pair while still have open positions, so those open positions also need to be considered
  - When enabling a new trading pair, because it may change threshold, we need to make sure it doesn't make a pool unsafe (pool wouldn't be margin called after this new pair. If it would, do not allow this new pair to be added)
- Trader threshold
  - The thresholds are configured per trading pair
  - The margin call / stop out liquidation threshold for a trader in a pool is the max of the threshold of all the trader opened pairs in the pool

For frontend considerations: Categories each trading pairs, and prevent pool owner to enable trading pairs in a pool with different category. Notice lp they should open a new pool instead.

**Comment by Antonia-Chen** [comment]
For frontend considerations: When enabling a new trading pair, check if it is in a different category, if so, notice lp they should open a new pool instead?
