### ISSUE TITLE
synthetic protocol RPC

### ISSUE THREAD

**Issue by xlc** [laminar-protocol/laminar-chain#201]
`synthetic_poolInfo`

Input: LiquidityPoolId, CurrencyId

Output:

collateral ratio
https://github.com/laminar-protocol/laminar-chain/blob/3efb3a138ad943b63ade269bcfb78cd13e86510f/modules/synthetic-protocol/src/lib.rs#L530

is safe
https://github.com/laminar-protocol/laminar-chain/blob/3efb3a138ad943b63ade269bcfb78cd13e86510f/modules/synthetic-protocol/src/lib.rs#L542

anything else useful?

**Comment by shaopengw** [comment]
`is_safe` and `collateral_ratio` should be enough for now, we could add more if needed later.
