### ISSUE TITLE
benchmarking

### ISSUE THREAD

**Issue by xlc** [laminar-protocol/laminar-chain#204]
Setup benchmarking

Something like
https://github.com/paritytech/substrate/blob/master/frame/balances/src/benchmarking.rs

- [x] base liquidity pools
- [x] margin liquidity pools
- [x] synthetic liquidity pools
- [x] margin protocol
- [x] synthetic protocol

**Comment by xlc** [comment]
Examples as be found at https://github.com/paritytech/substrate/issues/5596

**Comment by shaopengw** [comment]
Closed by #239 #251 #266
