### ISSUE TITLE
Return 1 instead of max_value

### ISSUE THREAD

**Issue by zjb0807** [laminar-protocol/laminar-chain#236]
`_enp_and_ell`  and  `margin_level`  will return max_value by default.
Should it return`Fixed128::from_natural(1);`(means `100%`) instead of max_value?

https://github.com/laminar-protocol/laminar-chain/blob/master/modules/margin-protocol/src/lib.rs#L816

https://github.com/laminar-protocol/laminar-chain/blob/master/modules/margin-protocol/src/lib.rs#L953-L957

**Comment by xlc** [comment]
The value can, and likely go above 100% so we can't use 1.

I think what we have is fine. Frontend can add logic to detect if value is > 1000%, change the display to something else.
