### ISSUE TITLE
Calculate enp/ell with spread.

### ISSUE THREAD

**Issue by zjb0807** [laminar-protocol/laminar-chain#283]
https://github.com/laminar-protocol/laminar-chain/blob/1e91d3bde237c78bb161b77c32fe2274556ae251/modules/margin-protocol/src/lib.rs#L1270-L1278

Here should use ask_price/bid_price and then convert to USD value to calculate net and max.

**Comment by zjb0807** [comment]
Need to discuss with @gorgos

**Comment by shaopengw** [comment]
Any reason to calculate it with spread? It's natural to take spread into consideration for traders, as spread is like 'loss' to them. But in the perspective of pools, spread is a 'profit' part of a position held.

**Comment by gorgos** [comment]
@shaopengw It's just slightly more accurate, but it's not important. The net position calculations are just for our safety functions, so not perfectly accurate is fine.

**Comment by shaopengw** [comment]
Why it's more accurate with spread?

**Comment by gorgos** [comment]
Because the net reflects the USD valuation of a position from a trader. Lets take USDEUR with 1 USD=2 EUR, 2% spread and a 1000 USD Long for example, he purchases 1000 USD, but what he actually holds is only 998 USD.

**Comment by shaopengw** [comment]
Only debit reflects spread. Held is the leveraged amount: https://github.com/laminar-protocol/laminar-chain/blob/c8844dcc9399d2e3bd2ab1df50d6c6acdac97042/modules/margin-protocol/src/lib.rs#L568
