### ISSUE TITLE
Rename flowchain to laminar-chain

### ISSUE THREAD

**Issue by xlc** [laminar-protocol/laminar-chain#37]
Use laminar-chain / LaminarChain instead of flowchain.

Make binary name `laminar`

**Comment by bette7** [comment]
Just as in fluid dynamics, laminar flow is characterized by fluid particles following smooth paths in layers, LaminarChain is set up to bring laminar-flow-like liquidity and trading experience between crypto and mainstream finance world.

All documentation and code referring to `flowchain` will also be renamed accordingly.

**Comment by zjb0807** [comment]
How to modify `Flow protocols`, `Flow Tokens`, `flowTokenAmount`, `FlowToken`, `fToken (Flow Token)` in the README file?

**Comment by xlc** [comment]
Keep them as it is. The chain is called Laminar Chain, the protocol Laminar Chain implements is Flow Protocol.
