### ISSUE TITLE
Use `ensure_can_withdraw` instead of balance check

### ISSUE THREAD

**Issue by xlc** [laminar-protocol/laminar-chain#39]
https://github.com/laminar-protocol/laminar-chain/blob/34e4f8e2b0f3ff8fa610521406cf481dc4a29aca/modules/synthetic-protocol/src/lib.rs#L172-L175

https://github.com/laminar-protocol/laminar-chain/blob/34e4f8e2b0f3ff8fa610521406cf481dc4a29aca/modules/synthetic-protocol/src/lib.rs#L224-L227

https://github.com/laminar-protocol/laminar-chain/blob/34e4f8e2b0f3ff8fa610521406cf481dc4a29aca/modules/synthetic-protocol/src/lib.rs#L245-L249

https://github.com/laminar-protocol/laminar-chain/blob/34e4f8e2b0f3ff8fa610521406cf481dc4a29aca/modules/synthetic-protocol/src/lib.rs#L273-L276

https://github.com/laminar-protocol/laminar-chain/blob/34e4f8e2b0f3ff8fa610521406cf481dc4a29aca/modules/synthetic-protocol/src/lib.rs#L317-L320

https://github.com/laminar-protocol/laminar-chain/blob/34e4f8e2b0f3ff8fa610521406cf481dc4a29aca/modules/synthetic-protocol/src/lib.rs#L345-L348

**Comment by zjb0807** [comment]
#42 has fixed.
