### ISSUE TITLE
Remove Leverage::LongOne / ShortOne and add can_mint

### ISSUE THREAD

**Issue by xlc** [laminar-protocol/laminar-chain#55]
Also replace is_allowed_position call in synthetic protocol to use can_mint

Part of #45 

Make sure laminar-chain.js is updated as well.

**Comment by ermalkaleci** [comment]
@xlc more details about `add can_mint`?

**Comment by xlc** [comment]
Add `can_mint(pool_id: Self::LiquidityPoolId, currency_id: Self::CurrencyId) -> bool` to https://github.com/laminar-protocol/laminar-chain/blob/f8d18304b5ae4e3eec9e895aa07bf7a3be4666c9/modules/traits/src/lib.rs#L23

**Comment by xlc** [comment]
Closed by #65
