### ISSUE TITLE
module-margin-protocol part 2

### ISSUE THREAD

**Issue by xlc** [laminar-protocol/laminar-chain#73]
Part of #45 
Depends on #72 

Remaining of module-margin-protocol without offchain worker part

- Types
  - struct RiskThreshold
    - margin_call: Permill
    - stop_out: Permill
- Trait
- Storage
  - MinLiquidationPercent: map TradingPair => SPercent
  - MarginCalledTraders: map AccountId => Option\<()>
  - MarginCalledLiquidatePools: map LiquidityPool => Option\<()>
  - TraderRiskThresholds: Option\<RiskThreshold>
  - LiquidityPoolENPThresholds: Option\<RiskThreshold>
  - LiquidityPoolELLThresholds: Option\<RiskThreshold>
- Constant
  - MaxPositionsCount: u16
- Call
  - trader_margin_call(origin, who: AccountId)
    - Does not need to check origin
  - trader_become_safe(origin, who: AccountId)
    - Does not need to check origin
  - trader_liquidate(origin, who: AccountId)
    - Does not need to check origin
  - liquidity_pool_margin_call(origin, pool: LiquidityPoolId)
    - Does not need to check origin
  - liquidity_pool_become_safe(origin, pool: LiquidityPoolId)
    - Does not need to check origin
  - liquidity_pool_liquidate(origin, pool: LiquidityPoolId)
    - Does not need to check origin
- Module
  - impl LiquidityPoolManager
    - prevent open new position for margin called pools

`SPercent`: signed percentage.

**Comment by shaopengw** [comment]
For `TraderRiskThresholds`, currently we would use a single setting for all traders, instead of per `TradingPair`. Same applies to `LiquidityPoolENPThresholds` and `LiquidityPoolELLThresholds`.

Note we need to review these threshold settings in the future, and might need to make them per liquidity pool.

**Comment by xlc** [comment]
Done
