### ISSUE TITLE
Margin Protocol: Trading Pair Management Draft

### ISSUE THREAD

**Issue by shaopengw** [laminar-protocol/laminar-chain#92]
In margin protocol, to make a trading pair available:
1. Firstly adding it in the protocol level, via a root call. (And make other resources available, like price feed.)
2. Liquidity providers could enable trading pairs which are in the protocol trading pair lists.

### Module liquidity pools
- Storage
  - MarginProtocolTradingPairs: map TradingPair => Option<()>
  - MarginProtocolLiquidityPoolTradingPairs: double_map LiquidityPoolId, TradingPair => Option<()>
- Dispatchable Calls
  - add_trading_pair(origin, pair: TradingPair);
    - root origin required (finance council?)

### MarginProtocolLiquidityPools trait
- add_trading_pair(pair: TradingPair) -> Result;
  - pool owner operation
  - must be in `MarginProtocolTradingPairs`

**Comment by zjb0807** [comment]
Implemented.
